// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "Vtop__Syms.h"
#include "Vtop_elementmixacc__Ec_F9_FB80_ECz3.h"

VL_ATTR_COLD void Vtop_elementmixacc__Ec_F9_FB80_ECz3___eval_static__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__rdlomixacc__BRA__0__KET____DOT__genblk1__DOT__rdlo0mixacc1(Vtop_elementmixacc__Ec_F9_FB80_ECz3* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+          Vtop_elementmixacc__Ec_F9_FB80_ECz3___eval_static__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__rdlomixacc__BRA__0__KET____DOT__genblk1__DOT__rdlo0mixacc1\n"); );
    // Body
    vlSelf->adcx_r = 0ULL;
    vlSelf->adcy_r = 0ULL;
    vlSelf->genblk1__BRA__0__KET____DOT__adcxi = 0U;
    vlSelf->genblk1__BRA__0__KET____DOT__adcyi = 0U;
    vlSelf->genblk1__BRA__0__KET____DOT__dloxi = 0U;
    vlSelf->genblk1__BRA__0__KET____DOT__dloyi = 0U;
    vlSelf->genblk1__BRA__0__KET____DOT__multixi_r = 0ULL;
    vlSelf->genblk1__BRA__0__KET____DOT__multiyi_r = 0ULL;
    vlSelf->genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__indexj = 0U;
    vlSelf->genblk1__BRA__1__KET____DOT__adcxi = 0U;
    vlSelf->genblk1__BRA__1__KET____DOT__adcyi = 0U;
    vlSelf->genblk1__BRA__1__KET____DOT__dloxi = 0U;
    vlSelf->genblk1__BRA__1__KET____DOT__dloyi = 0U;
    vlSelf->genblk1__BRA__1__KET____DOT__multixi_r = 0ULL;
    vlSelf->genblk1__BRA__1__KET____DOT__multiyi_r = 0ULL;
    vlSelf->genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__indexj = 0U;
    vlSelf->genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__indexj = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__adcxi = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__adcyi = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__dloxi = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__dloyi = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__multixi_r = 0ULL;
    vlSelf->genblk1__BRA__2__KET____DOT__multiyi_r = 0ULL;
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__indexj = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__indexj = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__indexj = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__adcxi = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__adcyi = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__dloxi = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__dloyi = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__multixi_r = 0ULL;
    vlSelf->genblk1__BRA__3__KET____DOT__multiyi_r = 0ULL;
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__indexj = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__indexj = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__indexj = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__indexi = 0U;
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__indexj = 0U;
    vlSelf->gatesr = 0U;
    vlSelf->gatesrdummy = 0U;
    vlSelf->accsumx = 0ULL;
    vlSelf->accsumy = 0ULL;
    vlSelf->newacc = 0U;
    vlSelf->accx_r = 0U;
    vlSelf->accy_r = 0U;
}

VL_ATTR_COLD void Vtop_elementmixacc__Ec_F9_FB80_ECz3___ctor_var_reset(Vtop_elementmixacc__Ec_F9_FB80_ECz3* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+          Vtop_elementmixacc__Ec_F9_FB80_ECz3___ctor_var_reset\n"); );
    // Body
    vlSelf->adcx = VL_RAND_RESET_Q(64);
    vlSelf->adcy = VL_RAND_RESET_Q(64);
    vlSelf->shift = VL_RAND_RESET_I(5);
    vlSelf->gateout = VL_RAND_RESET_I(1);
    vlSelf->stbout = VL_RAND_RESET_I(1);
    vlSelf->accx = VL_RAND_RESET_I(32);
    vlSelf->accy = VL_RAND_RESET_I(32);
    vlSelf->adcx_r = VL_RAND_RESET_Q(64);
    vlSelf->adcy_r = VL_RAND_RESET_Q(64);
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        for (int __Vi1 = 0; __Vi1 < 4; ++__Vi1) {
            vlSelf->multixi[__Vi0][__Vi1] = VL_RAND_RESET_Q(33);
        }
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        for (int __Vi1 = 0; __Vi1 < 4; ++__Vi1) {
            vlSelf->multiyi[__Vi0][__Vi1] = VL_RAND_RESET_Q(33);
        }
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->sumxslice[__Vi0] = VL_RAND_RESET_Q(34);
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->sumyslice[__Vi0] = VL_RAND_RESET_Q(34);
    }
    vlSelf->gatesr = VL_RAND_RESET_I(16);
    vlSelf->gatesrdummy = VL_RAND_RESET_I(1);
    vlSelf->sumxslicelast = VL_RAND_RESET_Q(50);
    vlSelf->sumyslicelast = VL_RAND_RESET_Q(50);
    vlSelf->accsumx = VL_RAND_RESET_Q(50);
    vlSelf->accsumy = VL_RAND_RESET_Q(50);
    vlSelf->newacc = VL_RAND_RESET_I(1);
    vlSelf->accx_r = VL_RAND_RESET_I(32);
    vlSelf->accy_r = VL_RAND_RESET_I(32);
    vlSelf->genblk1__BRA__0__KET____DOT__adcxi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__adcyi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__dloxi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__dloyi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__multixi_w = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__multiyi_w = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__multixi_r = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__multiyi_r = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__1__KET____DOT__adcxi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__adcyi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__dloxi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__dloyi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__multixi_w = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__multiyi_w = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__multixi_r = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__multiyi_r = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__2__KET____DOT__adcxi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__adcyi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__dloxi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__dloyi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__multixi_w = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__multiyi_w = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__multixi_r = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__multiyi_r = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__3__KET____DOT__adcxi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__adcyi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__dloxi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__dloyi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__multixi_w = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__multiyi_w = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__multixi_r = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__multiyi_r = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__indexi = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__indexj = VL_RAND_RESET_I(4);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xr = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__yr = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__yi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__zr = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__zi = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xi1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xi2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xi3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xi4 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xr1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xr2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xr3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__xr4 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__yi1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__yi2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__yi3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__yr1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__yr2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__yr3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__addcommon = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__addr = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__addi = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__mult0 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__multr = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__multi = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__zr_int = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__zi_int = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__common = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__commonr1 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__0__KET____DOT__mult1__DOT__commonr2 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xr = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__yr = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__yi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__zr = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__zi = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xi1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xi2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xi3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xi4 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xr1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xr2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xr3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__xr4 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__yi1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__yi2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__yi3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__yr1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__yr2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__yr3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__addcommon = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__addr = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__addi = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__mult0 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__multr = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__multi = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__zr_int = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__zi_int = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__common = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__commonr1 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__1__KET____DOT__mult1__DOT__commonr2 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xr = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__yr = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__yi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__zr = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__zi = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xi1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xi2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xi3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xi4 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xr1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xr2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xr3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__xr4 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__yi1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__yi2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__yi3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__yr1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__yr2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__yr3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__addcommon = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__addr = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__addi = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__mult0 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__multr = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__multi = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__zr_int = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__zi_int = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__common = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__commonr1 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__2__KET____DOT__mult1__DOT__commonr2 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__clk = VL_RAND_RESET_I(1);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xr = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__yr = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__yi = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__zr = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__zi = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xi1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xi2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xi3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xi4 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xr1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xr2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xr3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__xr4 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__yi1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__yi2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__yi3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__yr1 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__yr2 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__yr3 = VL_RAND_RESET_I(16);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__addcommon = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__addr = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__addi = VL_RAND_RESET_I(17);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__mult0 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__multr = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__multi = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__zr_int = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__zi_int = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__common = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__commonr1 = VL_RAND_RESET_Q(33);
    vlSelf->genblk1__BRA__3__KET____DOT__mult1__DOT__commonr2 = VL_RAND_RESET_Q(33);
}
