// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef _VTOP_ELEMENTCONN__PI3_H_
#define _VTOP_ELEMENTCONN__PI3_H_  // guard

#include "verilated.h"
#include "Vtop__Dpi.h"

//==========

class Vtop__Syms;
class Vtop_VerilatedFst;


//----------

VL_MODULE(Vtop_elementconn__pi3) {
  public:
    
    // PORTS
    VL_OUT16(envaddr,11,0);
    VL_OUT16(freqaddr,8,0);
    VL_IN(envdata,31,0);
    VL_INW(freqdata,127,0,4);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ busy;
        CData/*0:0*/ dummybusy;
        CData/*0:0*/ lastenv;
        CData/*0:0*/ envaddrdelay__DOT__clk;
        CData/*0:0*/ envaddrdelay__DOT__gate;
        CData/*0:0*/ envaddrdelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__clk;
        CData/*0:0*/ ammod__DOT__gatein;
        CData/*0:0*/ ammod__DOT__gateout;
        CData/*0:0*/ ammod__DOT__gphtime;
        CData/*0:0*/ ammod__DOT__gphaseinit;
        CData/*0:0*/ ammod__DOT__gcordic;
        CData/*0:0*/ ammod__DOT__gmulti;
        CData/*0:0*/ ammod__DOT__gateout_r;
        CData/*0:0*/ ammod__DOT__freqcossinpdelay__DOT__clk;
        CData/*0:0*/ ammod__DOT__freqcossinpdelay__DOT__gate;
        CData/*0:0*/ ammod__DOT__freqcossinpdelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__phtime__DOT__clk;
        CData/*0:0*/ ammod__DOT__phtime__DOT__gatein;
        CData/*0:0*/ ammod__DOT__phtime__DOT__gateout;
        CData/*7:0*/ ammod__DOT__phtime__DOT__gatesr;
        CData/*0:0*/ ammod__DOT__ampxdelay__DOT__clk;
        CData/*0:0*/ ammod__DOT__ampxdelay__DOT__gate;
        CData/*0:0*/ ammod__DOT__ampxdelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__pinidelay__DOT__clk;
        CData/*0:0*/ ammod__DOT__pinidelay__DOT__gate;
        CData/*0:0*/ ammod__DOT__pinidelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__clk;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__error;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__gin;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__gout;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__errorr;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__shiftpi;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__genblk6__DOT__xdummy;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__genblk6__DOT__ydummy;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__genblk6__DOT__zdummy;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__clk;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__gate;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__din;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__dout;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__reset;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__clk;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__gate;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__din;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__dout;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__clk;
    };
    struct {
        CData/*0:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__clk;
        SData/*11:0*/ envaddr_cnt;
        SData/*8:0*/ freqaddr_r;
        SData/*8:0*/ freqaddr_r2;
        SData/*8:0*/ freqaddr_r3;
        SData/*8:0*/ freqaddr_r4;
        SData/*11:0*/ envaddr_r;
        SData/*11:0*/ envaddr_r2;
        SData/*11:0*/ envaddr_r3;
        SData/*11:0*/ envaddrdelay__DOT__din;
        SData/*11:0*/ envaddrdelay__DOT__dout;
        SData/*15:0*/ ammod__DOT__ampx;
        SData/*15:0*/ ammod__DOT__ampx_d;
        SData/*15:0*/ ammod__DOT__ampx_d2;
        SData/*15:0*/ ammod__DOT__cos_w;
        SData/*15:0*/ ammod__DOT__sin_w;
        SData/*15:0*/ ammod__DOT__cos;
        SData/*15:0*/ ammod__DOT__sin;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__envxi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__envyi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__sinpi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__cospi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__envxi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__envyi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__sinpi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__cospi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__envxi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__envyi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__sinpi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__cospi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__envxi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__envyi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__sinpi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__cospi;
        SData/*15:0*/ ammod__DOT__ampxdelay__DOT__din;
        SData/*15:0*/ ammod__DOT__ampxdelay__DOT__dout;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xin;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yin;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xout;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yout;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xout_r;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yout_r;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xin_1;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yin_1;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xout1;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yout1;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__genblk3__DOT__xin_d;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__genblk3__DOT__yin_d;
        SData/*12:0*/ ammod__DOT__multidelay__DOT__usual__DOT__shifter;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr2;
    };
    struct {
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi;
    };
    struct {
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr4;
    };
    struct {
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yr3;
        WData/*127:0*/ freqdata_r[4];
        WData/*127:0*/ freqdata_r2[4];
        WData/*127:0*/ freqdata_r3[4];
        IData/*31:0*/ envdata_r;
        WData/*127:0*/ envdata_r3[4];
        WData/*127:0*/ envdata_r2[4];
        WData/*359:0*/ envaddrdelay__DOT__usual__DOT__shifter[12];
        IData/*26:0*/ ammod__DOT__tcnt;
        WData/*127:0*/ ammod__DOT__freqcossinp32x16[4];
        WData/*127:0*/ ammod__DOT__envxy32x16[4];
        IData/*16:0*/ ammod__DOT__pini;
        IData/*26:0*/ ammod__DOT__freq;
        IData/*31:0*/ ammod__DOT__freq32;
        WData/*127:0*/ ammod__DOT__freqcossinp32x16_d[4];
        IData/*26:0*/ ammod__DOT__phasetime;
        IData/*16:0*/ ammod__DOT__pini_d;
        IData/*16:0*/ ammod__DOT__phaseinit;
        WData/*127:0*/ ammod__DOT__freqcossinpdelay__DOT__din[4];
        WData/*127:0*/ ammod__DOT__freqcossinpdelay__DOT__dout[4];
        WData/*3199:0*/ ammod__DOT__freqcossinpdelay__DOT__usual__DOT__shifter[100];
        IData/*26:0*/ ammod__DOT__phtime__DOT__freq;
        IData/*26:0*/ ammod__DOT__phtime__DOT__tcnt;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime;
        IData/*26:0*/ ammod__DOT__phtime__DOT__freq_r;
        IData/*26:0*/ ammod__DOT__phtime__DOT__tcnt_r;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime_r0;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime_r1;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime_r2;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime_r3;
        WData/*111:0*/ ammod__DOT__ampxdelay__DOT__usual__DOT__shifter[4];
        IData/*16:0*/ ammod__DOT__pinidelay__DOT__din;
        IData/*16:0*/ ammod__DOT__pinidelay__DOT__dout;
        WData/*118:0*/ ammod__DOT__pinidelay__DOT__usual__DOT__shifter[4];
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phasein;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phaseout;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phaseout_r;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phasein_1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xg;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__yg;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__zg;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum0;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum2;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum2_d;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum3;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum0;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum2;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum2_d;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum3;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__zg0;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__zg1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phaseout1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__genblk3__DOT__phasein_d;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__znext;
    };
    struct {
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__yminus;
    };
    struct {
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__xnext;
    };
    struct {
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__zminus;
        IData/*19:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__usual__DOT__shifter;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__addi;
        QData/*41:0*/ busy_sr;
        QData/*63:0*/ ammod__DOT__multix16x16;
        QData/*63:0*/ ammod__DOT__multiy16x16;
        QData/*63:0*/ ammod__DOT__multix16x16_r;
        QData/*63:0*/ ammod__DOT__multiy16x16_r;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__zr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__zi1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__zr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__zi1;
    };
    struct {
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__zr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__zi1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__zr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__zi1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__zi;
        QData/*53:0*/ ammod__DOT__phtime__DOT__phasetime_w;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__mult0;
    };
    struct {
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__commonr2;
        SData/*15:0*/ ammod__DOT__cosp[4];
        SData/*15:0*/ ammod__DOT__sinp[4];
        SData/*15:0*/ ammod__DOT__envx[4];
        SData/*15:0*/ ammod__DOT__envy[4];
        SData/*15:0*/ ammod__DOT__multix[4];
        SData/*15:0*/ ammod__DOT__multiy[4];
        IData/*31:0*/ ammod__DOT__cordicg__DOT__PHASE[33];
        CData/*0:0*/ ammod__DOT__cordicg__DOT__plusall[17];
        CData/*0:0*/ ammod__DOT__cordicg__DOT__op[17];
        CData/*0:0*/ ammod__DOT__cordicg__DOT__pluscheck[17];
        CData/*0:0*/ ammod__DOT__cordicg__DOT__pluscheck0[17];
        IData/*16:0*/ ammod__DOT__cordicg__DOT__x[17];
        IData/*16:0*/ ammod__DOT__cordicg__DOT__y[17];
        IData/*16:0*/ ammod__DOT__cordicg__DOT__z[17];
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xshift[17];
        IData/*16:0*/ ammod__DOT__cordicg__DOT__yshift[17];
        IData/*16:0*/ ammod__DOT__cordicg__DOT__zshift[17];
    };
    
    // LOCAL VARIABLES
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v0;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v0;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v1;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v1;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v2;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v2;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v3;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v3;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v4;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v4;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v5;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v5;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v6;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v6;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v7;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v7;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v8;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v8;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v9;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v9;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v10;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v10;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v11;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v11;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v12;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v12;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v13;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v13;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v14;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v14;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck__v15;
        CData/*0:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__pluscheck0__v15;
        SData/*11:0*/ __Vdly__envaddr_cnt;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v0;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v0;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v0;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v1;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v1;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v1;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v2;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v2;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v2;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v3;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v3;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v3;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v4;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v4;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v4;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v5;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v5;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v5;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v6;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v6;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v6;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v7;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v7;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v7;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v8;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v8;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v8;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v9;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v9;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v9;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v10;
    };
    struct {
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v10;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v10;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v11;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v11;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v11;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v12;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v12;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v12;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v13;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v13;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v13;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v14;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v14;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v14;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v15;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v15;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v15;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__z__v16;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__x__v16;
        IData/*16:0*/ __Vdlyvval__ammod__DOT__cordicg__DOT__y__v16;
    };
    
    // INTERNAL VARIABLES
  private:
    Vtop__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vtop_elementconn__pi3);  ///< Copying not allowed
  public:
    Vtop_elementconn__pi3(const char* name = "TOP");
    ~Vtop_elementconn__pi3();
    
    // INTERNAL METHODS
    void __Vconfigure(Vtop__Syms* symsp, bool first);
    void _combo__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__0__KET____DOT__rdloelemconn__9(Vtop__Syms* __restrict vlSymsp);
    void _combo__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__1__KET____DOT__rdloelemconn__8(Vtop__Syms* __restrict vlSymsp);
    void _combo__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__2__KET____DOT__rdloelemconn__7(Vtop__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    void _initial__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__0__KET____DOT__rdloelemconn__1(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _multiclk__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__0__KET____DOT__rdloelemconn__21(Vtop__Syms* __restrict vlSymsp);
    void _multiclk__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__1__KET____DOT__rdloelemconn__20(Vtop__Syms* __restrict vlSymsp);
    void _multiclk__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__2__KET____DOT__rdloelemconn__19(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__0__KET____DOT__rdloelemconn__14(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__0__KET____DOT__rdloelemconn__15(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__0__KET____DOT__rdloelemconn__18(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__1__KET____DOT__rdloelemconn__12(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__1__KET____DOT__rdloelemconn__13(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__1__KET____DOT__rdloelemconn__17(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__2__KET____DOT__rdloelemconn__10(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__2__KET____DOT__rdloelemconn__11(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__2__KET____DOT__rdloelemconn__16(Vtop__Syms* __restrict vlSymsp);
    void _settle__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__0__KET____DOT__rdloelemconn__4(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__1__KET____DOT__rdloelemconn__5(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__dsp_sim_toplevel__DOT__dspmod__DOT__procinst__BRA__2__KET____DOT__rdloelemconn__6(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
  private:
    static void traceInit(void* userp, VerilatedFst* tracep, uint32_t code) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
