// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP_ELEMENTCONN__PI3_H_
#define VERILATED_VTOP_ELEMENTCONN__PI3_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_elementconn__pi3 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ busy;
        CData/*0:0*/ dummybusy;
        CData/*0:0*/ lastenv;
        CData/*0:0*/ envaddrdelay__DOT__clk;
        CData/*0:0*/ envaddrdelay__DOT__gate;
        CData/*0:0*/ envaddrdelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__clk;
        CData/*0:0*/ ammod__DOT__gatein;
        CData/*0:0*/ ammod__DOT__gateout;
        CData/*0:0*/ ammod__DOT__gphtime;
        CData/*0:0*/ ammod__DOT__gphaseinit;
        CData/*0:0*/ ammod__DOT__gcordic;
        CData/*0:0*/ ammod__DOT__gmulti;
        CData/*0:0*/ ammod__DOT__gateout_r;
        CData/*0:0*/ ammod__DOT__freqcossinpdelay__DOT__clk;
        CData/*0:0*/ ammod__DOT__freqcossinpdelay__DOT__gate;
        CData/*0:0*/ ammod__DOT__freqcossinpdelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__phtime__DOT__clk;
        CData/*0:0*/ ammod__DOT__phtime__DOT__gatein;
        CData/*0:0*/ ammod__DOT__phtime__DOT__gateout;
        CData/*7:0*/ ammod__DOT__phtime__DOT__gatesr;
        CData/*0:0*/ ammod__DOT__ampxdelay__DOT__clk;
        CData/*0:0*/ ammod__DOT__ampxdelay__DOT__gate;
        CData/*0:0*/ ammod__DOT__ampxdelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__pinidelay__DOT__clk;
        CData/*0:0*/ ammod__DOT__pinidelay__DOT__gate;
        CData/*0:0*/ ammod__DOT__pinidelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__clk;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__error;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__gin;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__gout;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__errorr;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__shiftpi;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__plus;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__genblk5__DOT__xdummy;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__genblk5__DOT__ydummy;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__genblk5__DOT__zdummy;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__clk;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__gate;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__din;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__dout;
        CData/*0:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__reset;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__clk;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__gate;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__din;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__dout;
        CData/*0:0*/ ammod__DOT__multidelay__DOT__reset;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__clk;
    };
    struct {
        CData/*0:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__clk;
        CData/*0:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__clk;
        VL_OUT16(envaddr,11,0);
        VL_OUT16(freqaddr,8,0);
        SData/*11:0*/ envaddr_cnt;
        SData/*8:0*/ freqaddr_r;
        SData/*8:0*/ freqaddr_r2;
        SData/*8:0*/ freqaddr_r3;
        SData/*8:0*/ freqaddr_r4;
        SData/*11:0*/ envaddr_r;
        SData/*11:0*/ envaddr_r2;
        SData/*11:0*/ envaddr_r3;
        SData/*11:0*/ envaddrdelay__DOT__din;
        SData/*11:0*/ envaddrdelay__DOT__dout;
        SData/*15:0*/ ammod__DOT__ampx;
        SData/*15:0*/ ammod__DOT__ampx_d;
        SData/*15:0*/ ammod__DOT__ampx_d2;
        SData/*15:0*/ ammod__DOT__cos_w;
        SData/*15:0*/ ammod__DOT__sin_w;
        SData/*15:0*/ ammod__DOT__cos;
        SData/*15:0*/ ammod__DOT__sin;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__envxi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__envyi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__sinpi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__cospi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__envxi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__envyi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__sinpi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__cospi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__envxi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__envyi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__sinpi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__cospi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__envxi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__envyi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__sinpi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__cospi;
        SData/*15:0*/ ammod__DOT__ampxdelay__DOT__din;
        SData/*15:0*/ ammod__DOT__ampxdelay__DOT__dout;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xin;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yin;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xout;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yout;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xout_r;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yout_r;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xin_1;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yin_1;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__xout1;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__yout1;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__genblk2__DOT__xin_d;
        SData/*15:0*/ ammod__DOT__cordicg__DOT__genblk2__DOT__yin_d;
        SData/*12:0*/ ammod__DOT__multidelay__DOT__usual__DOT__shifter;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xi4;
    };
    struct {
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__yr3;
    };
    struct {
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__yr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yr;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yi;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xi4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr2;
    };
    struct {
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__xr4;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yi1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yi2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yi3;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yr1;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yr2;
        SData/*15:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__yr3;
        VL_IN(envdata,31,0);
        VL_INW(freqdata,127,0,4);
        VlWide<4>/*127:0*/ freqdata_r;
        VlWide<4>/*127:0*/ freqdata_r2;
        VlWide<4>/*127:0*/ freqdata_r3;
        IData/*31:0*/ envdata_r;
        VlWide<4>/*127:0*/ envdata_r3;
        VlWide<4>/*127:0*/ envdata_r2;
        VlWide<12>/*359:0*/ envaddrdelay__DOT__usual__DOT__shifter;
        IData/*26:0*/ ammod__DOT__tcnt;
        VlWide<4>/*127:0*/ ammod__DOT__freqcossinp32x16;
        VlWide<4>/*127:0*/ ammod__DOT__envxy32x16;
        IData/*16:0*/ ammod__DOT__pini;
        IData/*26:0*/ ammod__DOT__freq;
        IData/*31:0*/ ammod__DOT__freq32;
        VlWide<4>/*127:0*/ ammod__DOT__freqcossinp32x16_d;
        IData/*26:0*/ ammod__DOT__phasetime;
        IData/*16:0*/ ammod__DOT__pini_d;
        IData/*16:0*/ ammod__DOT__phaseinit;
        VlWide<4>/*127:0*/ ammod__DOT__freqcossinpdelay__DOT__din;
        VlWide<4>/*127:0*/ ammod__DOT__freqcossinpdelay__DOT__dout;
        VlWide<104>/*3327:0*/ ammod__DOT__freqcossinpdelay__DOT__usual__DOT__shifter;
        IData/*26:0*/ ammod__DOT__phtime__DOT__freq;
        IData/*26:0*/ ammod__DOT__phtime__DOT__tcnt;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime;
        IData/*26:0*/ ammod__DOT__phtime__DOT__freq_r;
        IData/*26:0*/ ammod__DOT__phtime__DOT__tcnt_r;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime_r0;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime_r1;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime_r2;
        IData/*26:0*/ ammod__DOT__phtime__DOT__phasetime_r3;
        VlWide<5>/*159:0*/ ammod__DOT__ampxdelay__DOT__usual__DOT__shifter;
        IData/*16:0*/ ammod__DOT__pinidelay__DOT__din;
        IData/*16:0*/ ammod__DOT__pinidelay__DOT__dout;
        VlWide<6>/*169:0*/ ammod__DOT__pinidelay__DOT__usual__DOT__shifter;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phasein;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phaseout;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phaseout_r;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phasein_1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xg;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__yg;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__zg;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum0;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum2;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum2_d;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__xsum3;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum0;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum2;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum2_d;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__ysum3;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__zg0;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__zg1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__phaseout1;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__genblk2__DOT__phasein_d;
    };
    struct {
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__0__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__1__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__2__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__3__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__4__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__5__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__znext;
    };
    struct {
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__6__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__7__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__8__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__9__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__10__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__11__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__yminus;
    };
    struct {
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__12__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__13__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__14__KET____DOT__zminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__ain;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__xnext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__ynext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__znext;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__xplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__xminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__yplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__yminus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__zplus;
        IData/*16:0*/ ammod__DOT__cordicg__DOT__stage__BRA__15__KET____DOT__zminus;
        IData/*19:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__usual__DOT__shifter;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__addi;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__addcommon;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__addr;
        IData/*16:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__addi;
        QData/*41:0*/ busy_sr;
        QData/*63:0*/ ammod__DOT__multix16x16;
        QData/*63:0*/ ammod__DOT__multiy16x16;
        QData/*63:0*/ ammod__DOT__multix16x16_r;
        QData/*63:0*/ ammod__DOT__multiy16x16_r;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__zr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__zi1;
    };
    struct {
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__zr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__zi1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__zr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__zi1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__zr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__zi1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__zi;
        QData/*53:0*/ ammod__DOT__phtime__DOT__phasetime_w;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__commonr1;
    };
    struct {
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__commonr2;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__zr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__zi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__mult0;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__multr;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__multi;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__zr_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__zi_int;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__common;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__commonr1;
        QData/*32:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__commonr2;
        VlUnpacked<SData/*15:0*/, 4> ammod__DOT__cosp;
        VlUnpacked<SData/*15:0*/, 4> ammod__DOT__sinp;
        VlUnpacked<SData/*15:0*/, 4> ammod__DOT__envx;
        VlUnpacked<SData/*15:0*/, 4> ammod__DOT__envy;
        VlUnpacked<SData/*15:0*/, 4> ammod__DOT__multix;
        VlUnpacked<SData/*15:0*/, 4> ammod__DOT__multiy;
        VlUnpacked<IData/*31:0*/, 33> ammod__DOT__cordicg__DOT__PHASE;
        VlUnpacked<CData/*0:0*/, 17> ammod__DOT__cordicg__DOT__plusall;
        VlUnpacked<CData/*0:0*/, 17> ammod__DOT__cordicg__DOT__op;
        VlUnpacked<CData/*0:0*/, 17> ammod__DOT__cordicg__DOT__pluscheck;
        VlUnpacked<CData/*0:0*/, 17> ammod__DOT__cordicg__DOT__pluscheck0;
        VlUnpacked<IData/*16:0*/, 17> ammod__DOT__cordicg__DOT__x;
        VlUnpacked<IData/*16:0*/, 17> ammod__DOT__cordicg__DOT__y;
        VlUnpacked<IData/*16:0*/, 17> ammod__DOT__cordicg__DOT__z;
        VlUnpacked<IData/*16:0*/, 17> ammod__DOT__cordicg__DOT__xshift;
        VlUnpacked<IData/*16:0*/, 17> ammod__DOT__cordicg__DOT__yshift;
        VlUnpacked<IData/*16:0*/, 17> ammod__DOT__cordicg__DOT__zshift;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*0:0*/ ammod__DOT__cordicg__DOT__OPIN = 0U;
    static constexpr IData/*31:0*/ ENV_ADDRWIDTH = 0x0000000cU;
    static constexpr IData/*31:0*/ ENV_DATAWIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ FREQ_ADDRWIDTH = 9U;
    static constexpr IData/*31:0*/ FREQ_DATAWIDTH = 0x00000080U;
    static constexpr IData/*31:0*/ INTPRATIO = 4U;
    static constexpr IData/*31:0*/ NSLICE = 4U;
    static constexpr IData/*31:0*/ envaddrdelay__DOT__DW = 0x0000000cU;
    static constexpr IData/*31:0*/ envaddrdelay__DOT__LEN = 0x0000001eU;
    static constexpr IData/*31:0*/ ammod__DOT__NSLICE = 4U;
    static constexpr IData/*31:0*/ ammod__DOT__freqcossinpdelay__DOT__DW = 0x00000080U;
    static constexpr IData/*31:0*/ ammod__DOT__freqcossinpdelay__DOT__LEN = 0x0000001aU;
    static constexpr IData/*31:0*/ ammod__DOT__ampxdelay__DOT__DW = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__ampxdelay__DOT__LEN = 0x0000000aU;
    static constexpr IData/*31:0*/ ammod__DOT__pinidelay__DOT__DW = 0x00000011U;
    static constexpr IData/*31:0*/ ammod__DOT__pinidelay__DOT__LEN = 0x0000000aU;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__NSTAGE = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__NORMALIZE = 1U;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__ZWIDTH = 0x00000011U;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__BUFIN = 1U;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__GW = 1U;
    static constexpr VlWide<33>/*1055:0*/ ammod__DOT__cordicg__DOT__PHASE_CONST = {{
        0x20000000, 0x12e4051e, 0x09fb385b, 0x051111d4,
        0x028b0d43, 0x0145d7e1, 0x00a2f61e, 0x00517c55,
        0x0028be53, 0x00145f2f, 0x000a2f98, 0x000517cc,
        0x00028be6, 0x000145f3, 0x0000a2fa, 0x0000517d,
        0x000028be, 0x0000145f, 0x00000a30, 0x00000518,
        0x0000028c, 0x00000146, 0x000000a3, 0x00000051,
        0x00000029, 0x00000014, 0x0000000a, 0x00000005,
        0x00000003, 0x00000001, 0x00000001, 0x00000000,
        0x00000000
    }};
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__WIDTHP1 = 0x00000011U;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__BUFINDELAY = 1U;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__NORMALIZEDDELAY = 3U;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__DW = 1U;
    static constexpr IData/*31:0*/ ammod__DOT__cordicg__DOT__reg_delay__DOT__LEN = 0x00000014U;
    static constexpr IData/*31:0*/ ammod__DOT__multidelay__DOT__DW = 1U;
    static constexpr IData/*31:0*/ ammod__DOT__multidelay__DOT__LEN = 0x0000000dU;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__XWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult1__DOT__YWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__XWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__0__KET____DOT__mult2__DOT__YWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__XWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult1__DOT__YWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__XWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__1__KET____DOT__mult2__DOT__YWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__XWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult1__DOT__YWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__XWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__2__KET____DOT__mult2__DOT__YWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__XWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult1__DOT__YWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__XWIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ ammod__DOT__genblk2__BRA__3__KET____DOT__mult2__DOT__YWIDTH = 0x00000010U;

    // CONSTRUCTORS
    Vtop_elementconn__pi3(Vtop__Syms* symsp, const char* v__name);
    ~Vtop_elementconn__pi3();
    VL_UNCOPYABLE(Vtop_elementconn__pi3);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
