###############################################################################
# Timing Constraints
###############################################################################
# clock constraints
# 200 MHz system clock, moved to project top
create_clock -period 5.000 -name sysclk [get_ports SYSCLK_P]
create_clock -period 2.000 -name refclk_p_0 [get_ports refclk_p_0]
create_clock -period 4.000 -name core_clk_0 [get_ports {lmkclk_p_0[0]}]
create_clock -period 2.000 -name refclk_p_1 [get_ports refclk_p_1]
create_clock -period 4.000 -name core_clk_1 [get_ports {lmkclk_p_1[0]}]
# report_datasheet
# Source             |  Setup(ns) | Corner  |   Hold(ns)
# lmkclk_n_0[1]      |  0.870 (f) | SLOW    |  0.330 (f)
# lmkclk_n_1[1]      |  0.701 (f) | SLOW    |  0.225 (f)
set_input_delay -clock core_clk_0 -max 0.300 [get_ports {lmkclk_p_0[1]}]
set_input_delay -clock core_clk_0 -min -0.300 [get_ports {lmkclk_p_0[1]}]
set_input_delay -clock core_clk_1 -max 0.300 [get_ports {lmkclk_p_1[1]}]
set_input_delay -clock core_clk_1 -min -0.300 [get_ports {lmkclk_p_1[1]}]


set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
# clock constraints
# 200 MHz system clock, moved to project top
# create_clock -name sysclk -period 5.0 [get_ports SYSCLK_P]

# 200 MHz Clock input
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVDS} [get_ports SYSCLK_P]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVDS} [get_ports SYSCLK_N]
# I2C
set_property -dict {PACKAGE_PIN AT35 IOSTANDARD LVCMOS18} [get_ports I2C_SCL]
set_property -dict {PACKAGE_PIN AU32 IOSTANDARD LVCMOS18} [get_ports I2C_SDA]
set_property -dict {PACKAGE_PIN AY42 IOSTANDARD LVCMOS18} [get_ports I2C_MUX_RESET_B]

set_property -dict {PACKAGE_PIN AM39 IOSTANDARD LVCMOS18} [get_ports {GPIO_LED[0]}]
set_property -dict {PACKAGE_PIN AN39 IOSTANDARD LVCMOS18} [get_ports {GPIO_LED[1]}]
set_property -dict {PACKAGE_PIN AR37 IOSTANDARD LVCMOS18} [get_ports {GPIO_LED[2]}]
set_property -dict {PACKAGE_PIN AT37 IOSTANDARD LVCMOS18} [get_ports {GPIO_LED[3]}]
set_property -dict {PACKAGE_PIN AR35 IOSTANDARD LVCMOS18} [get_ports {GPIO_LED[4]}]
set_property -dict {PACKAGE_PIN AP41 IOSTANDARD LVCMOS18} [get_ports {GPIO_LED[5]}]
set_property -dict {PACKAGE_PIN AP42 IOSTANDARD LVCMOS18} [get_ports {GPIO_LED[6]}]
set_property -dict {PACKAGE_PIN AU39 IOSTANDARD LVCMOS18} [get_ports {GPIO_LED[7]}]

# USER SMA
set_property -dict {PACKAGE_PIN AN31 IOSTANDARD LVCMOS18} [get_ports USER_SMA_GPIO_P]
set_property -dict {PACKAGE_PIN AP31 IOSTANDARD LVCMOS18} [get_ports USER_SMA_GPIO_N]

# GPIO User Pushbuttons
set_property -dict {PACKAGE_PIN AV40 IOSTANDARD LVCMOS18} [get_ports CPU_RESET]
# set_property -dict "PACKAGE_PIN AP40 IOSTANDARD LVCMOS18" [get_ports GPIO_SW_S]
# set_property -dict "PACKAGE_PIN AR40 IOSTANDARD LVCMOS18" [get_ports GPIO_SW_N]
# set_property -dict "PACKAGE_PIN AV39 IOSTANDARD LVCMOS18" [get_ports GPIO_SW_C]
# set_property -dict "PACKAGE_PIN AU38 IOSTANDARD LVCMOS18" [get_ports GPIO_SW_E]
# set_property -dict "PACKAGE_PIN AW40 IOSTANDARD LVCMOS18" [get_ports GPIO_SW_W]

# set_property -dict "PACKAGE_PIN AV30 IOSTANDARD LVCMOS18" [get_ports {GPIO_DIP_SW[0]}]
# set_property -dict "PACKAGE_PIN AY33 IOSTANDARD LVCMOS18" [get_ports {GPIO_DIP_SW[1]}]
# set_property -dict "PACKAGE_PIN BA31 IOSTANDARD LVCMOS18" [get_ports {GPIO_DIP_SW[2]}]
# set_property -dict "PACKAGE_PIN BA32 IOSTANDARD LVCMOS18" [get_ports {GPIO_DIP_SW[3]}]
# set_property -dict "PACKAGE_PIN AW30 IOSTANDARD LVCMOS18" [get_ports {GPIO_DIP_SW[4]}]
# set_property -dict "PACKAGE_PIN AY30 IOSTANDARD LVCMOS18" [get_ports {GPIO_DIP_SW[5]}]
# set_property -dict "PACKAGE_PIN BA30 IOSTANDARD LVCMOS18" [get_ports {GPIO_DIP_SW[6]}]
# set_property -dict "PACKAGE_PIN BB31 IOSTANDARD LVCMOS18" [get_ports {GPIO_DIP_SW[7]}]

# FAN
# set_property -dict "PACKAGE_PIN BA37 IOSTANDARD LVCMOS18" [get_ports SM_FAN_PWM]
# set_property -dict "PACKAGE_PIN BB37 IOSTANDARD LVCMOS18" [get_ports SM_FAN_TACH]

# XADC
# set_property -dict "PACKAGE_PIN AN38 IOSTANDARD LVCMOS18" [get_ports XADC_VAUX0P_R]
# set_property -dict "PACKAGE_PIN AP38 IOSTANDARD LVCMOS18" [get_ports XADC_VAUX0N_R]
# set_property -dict "PACKAGE_PIN AM41 IOSTANDARD LVCMOS18" [get_ports XADC_VAUX8P_R]
# set_property -dict "PACKAGE_PIN AM42 IOSTANDARD LVCMOS18" [get_ports XADC_VAUX8N_R]
# set_property -dict "PACKAGE_PIN BA21 IOSTANDARD LVCMOS18" [get_ports {XADC_GPIO[0]}]
# set_property -dict "PACKAGE_PIN BB21 IOSTANDARD LVCMOS18" [get_ports {XADC_GPIO[1]}]
# set_property -dict "PACKAGE_PIN BB24 IOSTANDARD LVCMOS18" [get_ports {XADC_GPIO[2]}]
# set_property -dict "PACKAGE_PIN BB23 IOSTANDARD LVCMOS18" [get_ports {XADC_GPIO[3]}]

# BPI Flash
# https://www.xilinx.com/support/documentation/boards_and_kits/vc707/2014_4/xtp207-vc707-pcie-c-2014-4.pdf
set_property BITSTREAM.CONFIG.BPI_SYNC_MODE Type1 [current_design]
set_property CONFIG_MODE BPI16 [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN div-1 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
#set_property -dict "PACKAGE_PIN AP37 IOSTANDARD LVCMOS18" [get_ports FPGA_EMCCLK]

# UART
# Note: reversed UART TX/RX port name from ug885, from FPGA point of view
# UG885 Table 1-20
set_property -dict {PACKAGE_PIN AU36 IOSTANDARD LVCMOS18} [get_ports UART_TX]
set_property -dict {PACKAGE_PIN AU33 IOSTANDARD LVCMOS18} [get_ports UART_RX]
set_property -dict {PACKAGE_PIN AT32 IOSTANDARD LVCMOS18} [get_ports UART_CTS]
set_property -dict {PACKAGE_PIN AR34 IOSTANDARD LVCMOS18} [get_ports UART_RTS]

# LCD
# set_property -dict "PACKAGE_PIN AN41 IOSTANDARD LVCMOS18" [get_ports LCD_RS_LS]
# set_property -dict "PACKAGE_PIN AT40 IOSTANDARD LVCMOS18" [get_ports LCD_E_LS]
# set_property -dict "PACKAGE_PIN AR42 IOSTANDARD LVCMOS18" [get_ports LCD_RW_LS]
# set_property -dict "PACKAGE_PIN AT42 IOSTANDARD LVCMOS18" [get_ports LCD_DB4_LS]
# set_property -dict "PACKAGE_PIN AR38 IOSTANDARD LVCMOS18" [get_ports LCD_DB5_LS]
# set_property -dict "PACKAGE_PIN AR39 IOSTANDARD LVCMOS18" [get_ports LCD_DB6_LS]
# set_property -dict "PACKAGE_PIN AN40 IOSTANDARD LVCMOS18" [get_ports LCD_DB7_LS]
#ETHERNET
set_property -dict {PACKAGE_PIN AJ33 IOSTANDARD LVCMOS18} [get_ports PHY_RESET_LS]
set_property -dict {PACKAGE_PIN AK33 IOSTANDARD LVCMOS18} [get_ports PHY_MDIO_LS]
set_property -dict {PACKAGE_PIN AL31 IOSTANDARD LVCMOS18} [get_ports PHY_INT_LS]
set_property -dict {PACKAGE_PIN AH31 IOSTANDARD LVCMOS18} [get_ports PHY_MDC_LS]
set_property PACKAGE_PIN AH8 [get_ports SGMIICLK_Q0_P]
set_property PACKAGE_PIN AH7 [get_ports SGMIICLK_Q0_N]
set_property PACKAGE_PIN AM7 [get_ports SGMII_RX_N]
set_property PACKAGE_PIN AM8 [get_ports SGMII_RX_P]
set_property PACKAGE_PIN AN1 [get_ports SGMII_TX_N]
set_property PACKAGE_PIN AN2 [get_ports SGMII_TX_P]

# clock constraints
create_clock -period 8.000 -name sgmii_clk [get_ports SGMIICLK_Q0_P]

set_property IOSTANDARD LVDS [get_ports {lmkclk_*[*]}]
set_property DIFF_TERM true [get_ports {lmkclk_*[*]}]
set_property IOSTANDARD LVDS [get_ports dac_syncb_n_*]
set_property IOSTANDARD LVDS [get_ports dac_syncb_p_*]
set_property DIFF_TERM true [get_ports dac_syncb_n_*]
set_property DIFF_TERM true [get_ports dac_syncb_p_*]
set_property IOSTANDARD LVCMOS18 [get_ports dac_tx_en_*]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_syncb_*[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_*_over_range_*[*]}]
set_property IOSTANDARD LVDS [get_ports ext_trigger_*]
set_property DIFF_TERM true [get_ports ext_trigger_*]
set_property IOSTANDARD LVCMOS18 [get_ports fpga_trigger_*]
set_property IOSTANDARD LVDS [get_ports trig_sync_*]
set_property IOSTANDARD LVCMOS18 [get_ports lmk_sync_*]
set_property IOSTANDARD LVCMOS18 [get_ports pg_m2c_*]
set_property IOSTANDARD LVCMOS18 [get_ports prsnt_m2c_l_*]
set_property PACKAGE_PIN AM31 [get_ports prsnt_m2c_l_0]
set_property PACKAGE_PIN AN34 [get_ports pg_m2c_0]
set_property PACKAGE_PIN A10 [get_ports refclk_p_0]
set_property PACKAGE_PIN A9 [get_ports refclk_n_0]
set_property PACKAGE_PIN L39 [get_ports {lmkclk_p_0[0]}]
set_property PACKAGE_PIN L40 [get_ports {lmkclk_n_0[0]}]
set_property PACKAGE_PIN N30 [get_ports {lmkclk_p_0[1]}]
set_property PACKAGE_PIN M31 [get_ports {lmkclk_n_0[1]}]
#set_property PACKAGE_PIN E2 [get_ports serdout_p_0[0]]
#set_property PACKAGE_PIN E1 [get_ports serdout_n_0[0]]
set_property PACKAGE_PIN D7 [get_ports {serdin_n_0[0]}]
set_property PACKAGE_PIN D8 [get_ports {serdin_p_0[0]}]
#set_property PACKAGE_PIN D4 [get_ports serdout_p_0[1]]
#set_property PACKAGE_PIN D3 [get_ports serdout_n_0[1]]
set_property PACKAGE_PIN C5 [get_ports {serdin_n_0[1]}]
set_property PACKAGE_PIN C6 [get_ports {serdin_p_0[1]}]
#set_property PACKAGE_PIN C2 [get_ports serdout_p_0[2]]
#set_property PACKAGE_PIN C1 [get_ports serdout_n_0[2]]
set_property PACKAGE_PIN B7 [get_ports {serdin_n_0[2]}]
set_property PACKAGE_PIN B8 [get_ports {serdin_p_0[2]}]
#set_property PACKAGE_PIN B4 [get_ports serdout_p_0[3]]
#set_property PACKAGE_PIN B3 [get_ports serdout_n_0[3]]
set_property PACKAGE_PIN A5 [get_ports {serdin_n_0[3]}]
set_property PACKAGE_PIN A6 [get_ports {serdin_p_0[3]}]
#set_property PACKAGE_PIN J2 [get_ports serdout_p_0[4]]
#set_property PACKAGE_PIN J1 [get_ports serdout_n_0[4]]
set_property PACKAGE_PIN H7 [get_ports {serdin_n_0[4]}]
set_property PACKAGE_PIN H8 [get_ports {serdin_p_0[4]}]
#set_property PACKAGE_PIN H4 [get_ports serdout_p_0[5]]
#set_property PACKAGE_PIN H3 [get_ports serdout_n_0[5]]
set_property PACKAGE_PIN G5 [get_ports {serdin_n_0[5]}]
set_property PACKAGE_PIN G6 [get_ports {serdin_p_0[5]}]
#set_property PACKAGE_PIN G2 [get_ports serdout_p_0[6]]
#set_property PACKAGE_PIN G1 [get_ports serdout_n_0[6]]
set_property PACKAGE_PIN F7 [get_ports {serdin_n_0[6]}]
set_property PACKAGE_PIN F8 [get_ports {serdin_p_0[6]}]
#set_property PACKAGE_PIN F4 [get_ports serdout_p_0[7]]
#set_property PACKAGE_PIN F3 [get_ports serdout_n_0[7]]
set_property PACKAGE_PIN E5 [get_ports {serdin_n_0[7]}]
set_property PACKAGE_PIN E6 [get_ports {serdin_p_0[7]}]
set_property PACKAGE_PIN K39 [get_ports ext_trigger_p_0]
set_property PACKAGE_PIN K40 [get_ports ext_trigger_n_0]
set_property PACKAGE_PIN J40 [get_ports trig_sync_p_0]
set_property PACKAGE_PIN J41 [get_ports trig_sync_n_0]
set_property PACKAGE_PIN P41 [get_ports dac_syncb_p_0]
set_property PACKAGE_PIN N41 [get_ports dac_syncb_n_0]
set_property PACKAGE_PIN M41 [get_ports fpga_trigger_0]
set_property PACKAGE_PIN L41 [get_ports lmk_sync_0]
set_property PACKAGE_PIN K42 [get_ports {adc_syncb_0[1]}]
set_property PACKAGE_PIN J42 [get_ports {adc_syncb_0[0]}]
set_property PACKAGE_PIN G41 [get_ports {adc_a_over_range_0[0]}]
set_property PACKAGE_PIN G42 [get_ports {adc_b_over_range_0[0]}]
set_property PACKAGE_PIN M37 [get_ports {adc_a_over_range_0[1]}]
set_property PACKAGE_PIN M38 [get_ports {adc_b_over_range_0[1]}]
set_property PACKAGE_PIN R42 [get_ports dac_tx_en_0]
set_property PACKAGE_PIN AG32 [get_ports prsnt_m2c_l_1]
set_property PACKAGE_PIN AF29 [get_ports pg_m2c_1]
set_property PACKAGE_PIN K8 [get_ports refclk_p_1]
set_property PACKAGE_PIN K7 [get_ports refclk_n_1]
set_property PACKAGE_PIN AF39 [get_ports {lmkclk_p_1[0]}]
set_property PACKAGE_PIN AF40 [get_ports {lmkclk_n_1[0]}]
set_property PACKAGE_PIN U39 [get_ports {lmkclk_p_1[1]}]
set_property PACKAGE_PIN T39 [get_ports {lmkclk_n_1[1]}]
#set_property PACKAGE_PIN N2 [get_ports serdout_p_1[0]]
#set_property PACKAGE_PIN N1 [get_ports serdout_n_1[0]]
set_property PACKAGE_PIN P7 [get_ports {serdin_n_1[0]}]
set_property PACKAGE_PIN P8 [get_ports {serdin_p_1[0]}]
#set_property PACKAGE_PIN M4 [get_ports serdout_p_1[1]]
#set_property PACKAGE_PIN M3 [get_ports serdout_n_1[1]]
set_property PACKAGE_PIN N5 [get_ports {serdin_n_1[1]}]
set_property PACKAGE_PIN N6 [get_ports {serdin_p_1[1]}]
#set_property PACKAGE_PIN L2 [get_ports serdout_p_1[2]]
#set_property PACKAGE_PIN L1 [get_ports serdout_n_1[2]]
set_property PACKAGE_PIN L5 [get_ports {serdin_n_1[2]}]
set_property PACKAGE_PIN L6 [get_ports {serdin_p_1[2]}]
#set_property PACKAGE_PIN K4 [get_ports serdout_p_1[3]]
#set_property PACKAGE_PIN K3 [get_ports serdout_n_1[3]]
set_property PACKAGE_PIN J5 [get_ports {serdin_n_1[3]}]
set_property PACKAGE_PIN J6 [get_ports {serdin_p_1[3]}]
#set_property PACKAGE_PIN U2 [get_ports serdout_p_1[4]]
#set_property PACKAGE_PIN U1 [get_ports serdout_n_1[4]]
set_property PACKAGE_PIN W5 [get_ports {serdin_n_1[4]}]
set_property PACKAGE_PIN W6 [get_ports {serdin_p_1[4]}]
#set_property PACKAGE_PIN T4 [get_ports serdout_p_1[5]]
#set_property PACKAGE_PIN T3 [get_ports serdout_n_1[5]]
set_property PACKAGE_PIN V3 [get_ports {serdin_n_1[5]}]
set_property PACKAGE_PIN V4 [get_ports {serdin_p_1[5]}]
#set_property PACKAGE_PIN R2 [get_ports serdout_p_1[6]]
#set_property PACKAGE_PIN R1 [get_ports serdout_n_1[6]]
set_property PACKAGE_PIN U5 [get_ports {serdin_n_1[6]}]
set_property PACKAGE_PIN U6 [get_ports {serdin_p_1[6]}]
#set_property PACKAGE_PIN P4 [get_ports serdout_p_1[7]]
#set_property PACKAGE_PIN P3 [get_ports serdout_n_1[7]]
set_property PACKAGE_PIN R5 [get_ports {serdin_n_1[7]}]
set_property PACKAGE_PIN R6 [get_ports {serdin_p_1[7]}]
set_property PACKAGE_PIN AD40 [get_ports ext_trigger_p_1]
set_property PACKAGE_PIN AD41 [get_ports ext_trigger_n_1]
set_property PACKAGE_PIN AF41 [get_ports trig_sync_p_1]
set_property PACKAGE_PIN AG41 [get_ports trig_sync_n_1]
set_property PACKAGE_PIN AK39 [get_ports dac_syncb_p_1]
set_property PACKAGE_PIN AL39 [get_ports dac_syncb_n_1]
set_property PACKAGE_PIN AF42 [get_ports fpga_trigger_1]
set_property PACKAGE_PIN AG42 [get_ports lmk_sync_1]
set_property PACKAGE_PIN AD38 [get_ports {adc_syncb_1[1]}]
set_property PACKAGE_PIN AE38 [get_ports {adc_syncb_1[0]}]
set_property PACKAGE_PIN AC40 [get_ports {adc_a_over_range_1[0]}]
set_property PACKAGE_PIN AC41 [get_ports {adc_b_over_range_1[0]}]
set_property PACKAGE_PIN AD42 [get_ports {adc_a_over_range_1[1]}]
set_property PACKAGE_PIN AE42 [get_ports {adc_b_over_range_1[1]}]
set_property PACKAGE_PIN AJ38 [get_ports dac_tx_en_1]





