create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name iladsp
set_property -dict {
CONFIG.C_PROBE0_TYPE {0}
CONFIG.C_PROBE0_WIDTH {16}
CONFIG.C_PROBE1_TYPE {0}
CONFIG.C_PROBE1_WIDTH {16}
CONFIG.C_PROBE2_TYPE {0}
CONFIG.C_PROBE2_WIDTH {16}
CONFIG.C_PROBE3_TYPE {0}
CONFIG.C_PROBE3_WIDTH {16}
CONFIG.C_PROBE4_TYPE {0}
CONFIG.C_PROBE4_WIDTH {16}
CONFIG.C_PROBE5_TYPE {0}
CONFIG.C_PROBE5_WIDTH {16}
CONFIG.C_PROBE6_TYPE {0}
CONFIG.C_PROBE6_WIDTH {1}
CONFIG.C_PROBE7_TYPE {0}
CONFIG.C_PROBE7_WIDTH {4}
CONFIG.C_PROBE8_TYPE {0}
CONFIG.C_PROBE8_WIDTH {4}
CONFIG.C_PROBE9_TYPE {0}
CONFIG.C_PROBE9_WIDTH {1}
CONFIG.C_PROBE10_TYPE {0}
CONFIG.C_PROBE10_WIDTH {4}
CONFIG.C_PROBE11_TYPE {0}
CONFIG.C_PROBE11_WIDTH {4}
CONFIG.C_PROBE12_TYPE {0}
CONFIG.C_PROBE12_WIDTH {4}
CONFIG.C_PROBE13_TYPE {0}
CONFIG.C_PROBE13_WIDTH {4}
CONFIG.C_PROBE14_TYPE {0}
CONFIG.C_PROBE14_WIDTH {4}
CONFIG.C_PROBE15_TYPE {0}
CONFIG.C_PROBE15_WIDTH {4}
CONFIG.C_PROBE16_TYPE {0}
CONFIG.C_PROBE16_WIDTH {4}
CONFIG.C_PROBE17_TYPE {0}
CONFIG.C_PROBE17_WIDTH {4}
CONFIG.C_PROBE18_TYPE {0}
CONFIG.C_PROBE18_WIDTH {13}
CONFIG.C_PROBE19_TYPE {0}
CONFIG.C_PROBE19_WIDTH {64}
CONFIG.C_PROBE20_TYPE {0}
CONFIG.C_PROBE20_WIDTH {5}
CONFIG.C_PROBE21_TYPE {0}
CONFIG.C_PROBE21_WIDTH {5}
CONFIG.C_PROBE22_TYPE {0}
CONFIG.C_PROBE22_WIDTH {16}
CONFIG.C_PROBE23_TYPE {0}
CONFIG.C_PROBE23_WIDTH {16}
CONFIG.C_PROBE24_TYPE {0}
CONFIG.C_PROBE24_WIDTH {16}
CONFIG.C_NUM_OF_PROBES {25}
} [get_ips iladsp]
#generate_target {instantiation_template} [get_files iladsp.xci]
#generate_target all [get_files  iladsp.xci]
#export_ip_user_files -of_objects [get_files iladsp.xci] -no_script -sync -force -quiet
#create_ip_run [get_files -of_objects [get_fileset sources_1] iladsp.xci]
#CONFIG.C_EN_STRG_QUAL {1}
#CONFIG.C_TRIGIN_EN {true}
